[build.environment]
  HUGO_VERSION = "0.132.0"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run preview"

[dev]
  framework = "hugo"
  targetPort = 3000
